import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import csv from 'csv-parser';
import QRCode from 'qrcode';

const WORDS_CSV_PATH = path.join(process.cwd(), 'data', 'words.csv');
const QR_ASSETS_DIR = path.join(process.cwd(), 'qr-assets');
const MANIFEST_PATH = path.join(process.cwd(), 'data', 'qr-manifest.csv');
const SQL_SEED_PATH = path.join(process.cwd(), 'supabase', '04_seed.sql');

// You should set this in your environment or change it before running
const BASE_DOMAIN = process.env.VITE_GAME_DOMAIN || 'https://engomarabd-elaziz.github.io/Qr_Hunt_Web';

// Cryptographically secure token generator
function generateToken(length = 10) {
    return crypto.randomBytes(length).toString('base64url').substring(0, length);
}

// Generate an SVG QR code with a letter centered
async function generateQRWithLetterSVG(token, letter, outputDir, word, index) {
    const url = `${BASE_DOMAIN}/f/${token}`;
    
    // Ensure directory exists
    const wordDir = path.join(outputDir, word);
    if (!fs.existsSync(wordDir)) {
        fs.mkdirSync(wordDir, { recursive: true });
    }

    const svgString = await QRCode.toString(url, {
        type: 'svg',
        errorCorrectionLevel: 'H',
        margin: 4,
        color: {
            dark: '#000000',
            light: '#ffffff'
        }
    });

    // The generated SVG doesn't natively have a center overlay feature, 
    // so we can manually manipulate the SVG string to add a text overlay
    
    // Find the closing </svg> tag
    const closingTagIndex = svgString.indexOf('</svg>');
    
    // We add a white circle background for the letter, then the text itself.
    // Assuming viewBox is roughly "0 0 45 45" (depends on QR density)
    // Actually qrcode module outputs width/height attributes and viewBox.
    // We'll use a relative percentage for positioning.
    const overlay = `
        <circle cx="50%" cy="50%" r="12%" fill="white" />
        <text x="50%" y="50%" font-family="Arial, sans-serif" font-size="6" font-weight="bold" fill="black" text-anchor="middle" dominant-baseline="central">${letter}</text>
    `;
    
    const finalSVG = svgString.slice(0, closingTagIndex) + overlay + '</svg>';
    
    const filename = `${word}-${letter}-${index}.svg`;
    const filepath = path.join(wordDir, filename);
    
    fs.writeFileSync(filepath, finalSVG);
    
    // Optional: Generate PNG
    const pngFilepath = path.join(wordDir, `${word}-${letter}-${index}.png`);
    await QRCode.toFile(pngFilepath, url, {
        errorCorrectionLevel: 'H',
        margin: 4,
        width: 300
    });

    return filename;
}

async function main() {
    const words = [];
    
    console.log('Reading Word Pool...');
    await new Promise((resolve) => {
        fs.createReadStream(WORDS_CSV_PATH)
            .pipe(csv())
            .on('data', (row) => words.push(row))
            .on('end', resolve);
    });

    console.log(`Loaded ${words.length} words.`);

    // Clear assets
    if (fs.existsSync(QR_ASSETS_DIR)) {
        fs.rmSync(QR_ASSETS_DIR, { recursive: true, force: true });
    }
    fs.mkdirSync(QR_ASSETS_DIR, { recursive: true });

    let manifestLines = ['fragment_id,public_token,word,letter,hint,qr_filename'];
    let sqlSeedLines = [
        '-- supabase/04_seed.sql',
        '-- Autogenerated seed data for words and fragments',
        'BEGIN;',
        ''
    ];

    const allFragments = [];
    
    for (const row of words) {
        const wordText = row.word.toUpperCase();
        const wordId = crypto.randomUUID();
        
        sqlSeedLines.push(`INSERT INTO words (id, word, length, status) VALUES ('${wordId}', '${wordText}', ${wordText.length}, 'HIDDEN');`);
        
        for (let i = 0; i < wordText.length; i++) {
            const letter = wordText[i];
            const token = generateToken(10);
            const fragmentId = crypto.randomUUID();
            const hint = `A fragment of length ${wordText.length}`;
            
            console.log(`Generating QR for ${wordText} - ${letter} (${token})`);
            
            const filename = await generateQRWithLetterSVG(token, letter, QR_ASSETS_DIR, wordText, i);
            
            manifestLines.push(`${fragmentId},${token},${wordText},${letter},"${hint}",${filename}`);
            
            sqlSeedLines.push(`INSERT INTO fragments (id, public_token, word_id, letter, hint, status) VALUES ('${fragmentId}', '${token}', '${wordId}', '${letter}', '${hint}', 'AVAILABLE');`);
            
            allFragments.push({ fragmentId, token, wordText, letter, hint, filename });
        }
        sqlSeedLines.push('');
    }

    sqlSeedLines.push('COMMIT;');

    fs.writeFileSync(MANIFEST_PATH, manifestLines.join('\n'));
    fs.writeFileSync(SQL_SEED_PATH, sqlSeedLines.join('\n'));

    console.log(`\nGenerated ${allFragments.length} physical fragments across ${words.length} words.`);
    console.log('Manifest written to:', MANIFEST_PATH);
    console.log('SQL Seed written to:', SQL_SEED_PATH);
}

main().catch(console.error);
